#!/bin/bash

read -t1;

if [ -z "$REPLY" ]; then
    REPLY="";
    args="$@";
else
    args=" $@";
fi;

values="$REPLY";
values+="$args";

echo $values | sort | tr " " "\n" | uniq -c | tail -n 1 | xargs | cut -d" " -f2;

