#!/bin/bash

read -t1;

if [ -z "$REPLY" ]; then
    REPLY="";
    args="$@";
    # only use args that are passed in, no space
else
    args=" $@";
    # args to append later
fi;

values="$REPLY";
values+="$args";

vals="$(echo "$values" | freq | cut -d" " -f1)";
freqs="$(echo "$values" | freq | cut -d" " -f2)";

cum_freqs="$(echo "$freqs" | head -n 1)";

prev="$cum_freqs";

for f in ${freqs:1}; do
    #echo "prev: $prev";
    #echo "f: $f";
    prev="$(echo "$prev + $f" | bc -l)";
    cum_freqs+=" $prev";
    #sum="$(echo "$f + $prev" | bc -l)";
    #cum_freqs+=" $sum";
    #prev="$sum";
done;

while getopts 'ah' OPTION; do
    case "$OPTION" in
	a)
	    arrows="true"
	    ;;
	h)
	    header="true"
	    ;;
	*)
	    echo "usage: $(echo "$(basename $0)") [-a] [-h]" >&2
	    exit 1
	    ;;
    esac;
done;

arrow_var=" ";

if [ "$arrows" = "true" ]; then
    arrow_var="->";
    if [ "$header" = "true" ]; then
	echo "V${arrow_var}F";
	header="false";
    fi;
fi;

if [ "$header" = "true" ]; then
    echo "V CF"
fi;


paste -d"$arrow_var" <(echo "$vals") \
      <(echo "$cum_freqs" | tr " " "\n") | sed "s/-/->/g" |
    grep -E "(V${arrow_var}CF|[0-9]+\.?[0-9]+?${arrow_var}[0-9]+)" |
    sort -n;
