#!/bin/bash

read -t1;

if [ -z "$REPLY" ]; then
    REPLY="";
    args="$@";
else
    args=" $@";
fi;

values="$REPLY";
values+="$args";

while getopts 'ah' OPTION; do
    case "$OPTION" in
	a)
	    arrows="true"
	    ;;
	h)
	    header="true"
	    ;;
	*)
	    echo "usage: $(echo "$(basename $0)") [-a] [-h]" >&2
	    exit 1
	    ;;
    esac;
done;
# uniq requires newlines and things being sorted
#echo "V>F"
#prints the value then the freq

arrow_var=" "

if [ "$arrows" = "true" ]; then
    arrow_var="->";
    if [ "$header" = "true" ]; then
	echo "V${arrow_var}F";
	header="false";
    fi;
fi;

if [ "$header" = "true" ]; then
    echo "V F"
fi;
echo "$values" | tr " " "\n" | sort | uniq -c |
    grep -E "[0-9]+ [0-9]+" | sed -E "s/(\ ){2,}//g"| sed "s/\ /~/g" |
    awk -F "~" '{ print $2 "~" $1}' | sed "s/~/$arrow_var/g" | sort -n;
#echo "$table" | cut -d"~" -f2;
#echo "$table" | cut -d"~" -f1;
