#!/bin/bash

# reading from stdin
read -t1;

# seeing if the $REPLY is empty
if [ -z "$REPLY" ]; then
    REPLY="";
    args="$@";
    # only use args that are passed in, no space
else
    args=" $@";
    # args to append later
fi;

values="$REPLY";
values+="$args";

word_count="$(echo "$values" | wc -w )";

echo "$word_count"

# sum dependency
summation="$(sum "$values")";

echo "$summation / $word_count" | bc -l;
