#!/bin/bash

read -t1;

if [ -z "$REPLY" ]; then
    REPLY="";
    args="$@";
else
    args=" $@";
fi;

values="$REPLY";
values+="$args";

echo "$values" | ./freq | sort -t " " -k2n | tail -n 1 | cut -d " " -f 1;
