#!/bin/bash

# std deviation is the sqrt of the sum of all args minus the mean over amount of args

read -t1;

if [ -z "$REPLY" ]; then
    REPLY="";
    args="$@";
else
    args=" $@";
fi;

values="$REPLY";
values+="$args";

variance_value="$(echo "$values" | variance)";

echo "sqrt($variance_value)" | bc -l;
