#!/bin/bash

# std deviation is the sqrt of the sum of all args minus the mean over amount of args

read -t1;

if [ -z "$REPLY" ]; then
    REPLY="";
    args="$@";
else
    args=" $@";
fi;

values="$REPLY";
values+="$args";

word_count="$(echo "$values" | wc -w)";

word_count="$(echo "$word_count -1" | bc -l)";

mean="$(echo "$values" | mean)";

summation=0;

for val in $REPLY; do
    remainder="$(echo "$val - $mean" | bc -l)";
    remainder_squared="$(echo "$remainder ^ 2" | bc -l)";
    summation="$(echo "$remainder_squared + $summation" | bc -l)";
done;

sum_over_count="$(echo "$summation / $word_count" | bc -l)";

echo "sqrt($sum_over_count)" | bc -l;
