#!/bin/bash

read -t1;

if [ -z "$REPLY" ]; then
    REPLY="";
    args="$@";
else
    args=" $@";
fi;
values="$REPLY";
values+="$args";


square_sum=0;
echo $values | tr " " "\n" | awk '{ print $1 ^ 2}' | xargs | ./sum;
